version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      ADDRESS: ${ADDRESS}
      PORT: ${PORT}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    networks:
      - kafka-nework
  zookeeper:
    image: "bitnami/zookeeper:3.7"
    restart: always
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-nework
    # message broker - kafka
    # reference: https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml
  kafka:
    image: "bitnami/kafka:latest"
    restart: always
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"

    ports:
      - "9092:9092"
    networks:
      - kafka-nework
    depends_on:
      - zookeeper
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

    networks:
      - kafka-nework
networks:
  kafka-nework:
    driver: bridge
